
results_per_page: 10

# Set the width you prefer for the images and videos in your async results
# set to null to use original size.
thumbnail_width: 400
thumbnail_height: 300

# Use our default styles, or provide your own.
default_style: true

# Define the color for the instagram-link to your media posts.
icon_color: 'rgba(200, 200, 200, 1)'
overlay_color: 'rgba(0, 0, 0, 0.6)'

# Show a link for 'Follow on Instagram'
show_follow_on_instagram: true
follow_classname: 'instagram-follow--right'

upload_location: 'files/instagram'
max_upload_size: 8M

# Set this to true if you want to display videos in your feed.
allow_video: false

# Set this to true if you want to host instagram videos on your server.
store_video: false