
results_per_page: 10

# Set the width you prefer for the images in your async results
async_thumbnail_width: 400
async_video_width: 400

default_style: true
icon_color: '#cdcdcd'

# Show a link for 'Follow on Instagram'
show_follow_on_instagram: true
follow_classname: 'instagram-follow--right'

upload_location: 'files/instagram'
max_upload_size: 8M

# Set this to true if you want to display videos in your feed.
allow_video: false

# Set this to true if you want to host instagram videos on your server.
store_video: false